# Generated by Django 4.2.2 on 2023-06-07 03:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(db_index=True, max_length=256)),
                ('email', models.EmailField(help_text='Por favor, introduce una dirección de correo electrónico válida.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('fecha_nacimiento', models.DateField(help_text='La fecha no puede ser inferios a 1950-1-1', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1950, 1, 1))])),
                ('numero_documento', models.IntegerField(help_text='El campo debe ser mayor a 8 digitos', validators=[django.core.validators.MinLengthValidator(8)])),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_index=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-id'],
            },
            managers=[
                ('objects_', django.db.models.manager.Manager()),
            ],
        ),
    ]
