# Generated by Django 4.2.2 on 2023-06-07 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(help_text='El campo debe ser mayor a 8 digitos', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
